apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
agents: 2
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
    - loadbalancer
hostAliases:
  - ip: 10.0.2.15
    hostnames:
      - gitlab.concombre.toboggan
registries:
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - https://nexus.42lyon.fr:5000
