apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: gitlab-pool
spec:
  addresses:
  - 172.22.255.200-172.22.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  namespace: metallb-system
  name: gitlab-advert
spec:
  ipAddressPools:
  - gitlab-pool
